RentalOfProperty/RentalOfProperty.WebUserInterface/Controllers/AdsController.cs
namespace RentalOfProperty.WebUserInterface.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using RentalOfProperty.BusinessLogicLayer.Interfaces;
    using RentalOfProperty.BusinessLogicLayer.Models;
    using RentalOfProperty.WebUserInterface.Enums;
    using RentalOfProperty.WebUserInterface.Models.Ad;
    using BLLLoadDataFromSourceMenu = BusinessLogicLayer.Enums.LoadDataFromSourceMenu;
    using BLLAdsTypeMenu = BusinessLogicLayer.Enums.AdsTypeMenu;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using RentalOfProperty.WebUserInterface.Models;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Hosting;
    using System.IO;
    using Microsoft.Extensions.Localization;

    /// <summary>
    /// Ads controller.
    /// </summary>
    public class AdsController : Controller
    {
        private const int DefaultPage = 1;

        private const int PageSize = 30;

        private readonly ILogger<AdsController> _logger;

        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        private readonly IAdsManager _adsManager;

        private readonly IUsersManager _usersManager;

        private readonly IWebHostEnvironment _applicationEnvironment;

        private readonly IMapper _mapper;

        public const string ImagePath = @"\Files\RentalOfPropertyPhotos\";

        /// <summary>
        /// Initializes a new instance of the <see cref="AdsController"/> class.
        /// </summary>
        /// <param name="adsManager">Ads manager model.</param>
        /// <param name="usersManager">Users manager model.</param>
        /// <param name="mapper">Mapper model..</param>
        /// <param name="logger">Error logger.</param>
        public AdsController(IAdsManager adsManager, IUsersManager usersManager, IMapper mapper, ILogger<AdsController> logger, IWebHostEnvironment applicationEnvironment)
        {
            _adsManager = adsManager;
            _usersManager = usersManager;
            _mapper = mapper;
            _logger = logger;
            _applicationEnvironment = applicationEnvironment;
        }

        /// <summary>
        /// All info about rental ad.
        /// </summary>
        /// <param name="id">Unique key.</param>
        /// <returns>Action result object.</returns>
        public async Task<IActionResult> RentalAd(string id)
        {
            try
            {
                var allRentalAdInfo = await _adsManager.GetAllRentalAdInfo(id);
                var allRentalAdInfoView = new AllRentalAdInfoView
                {
                    AditionalAdData = _mapper.Map<AditionalAdDataView>(allRentalAdInfo.AditionalAdData),
                    ContactPerson = _mapper.Map<ContactPersonView>(allRentalAdInfo.ContactPerson),
                    Photos = _mapper.Map<IEnumerable<HousingPhotoView>>(allRentalAdInfo.Photos),
                    IsOriginal = allRentalAdInfo.IsOriginal,
                };
                var userId = User.Identity.Name is null ? default : _usersManager.FindByEmail(User.Identity.Name).Id;
                var userFavoriteAds = userId is null ? default : await _adsManager.GetUserFavoriteAds(userId);

                if (allRentalAdInfo.RentalAd is DailyRentalAd)
                {
                    allRentalAdInfoView.RentalAd = _mapper.Map<DailyRentalAdView>(allRentalAdInfo.RentalAd);
                }
                else
                {
                    allRentalAdInfoView.RentalAd = _mapper.Map<LongTermRentalAdView>(allRentalAdInfo.RentalAd);
                }

                if (!(userFavoriteAds is null))
                {
                    allRentalAdInfoView.RentalAd.IsFavorite = userFavoriteAds.FirstOrDefault(userAd => userAd.RentalAdId.Equals(allRentalAdInfoView.RentalAd.Id) && userAd.UserId.Equals(userId)) is null ? false : true;
                }

                allRentalAdInfoView.MapPlace = new MapPlace
                {
                    GeoLong = allRentalAdInfo.RentalAd.XMapCoordinate,
                    GeoLat = allRentalAdInfo.RentalAd.YMapCoordinate,
                };

                return View(allRentalAdInfoView);
            }
            catch (Exception exception)
            {
                _logger.LogError($"Error : {exception.Message}");
                return RedirectToAction("Index", "Home");
            }
        }

        /// <summary>
        /// Cities statistic.
        /// </summary>
        /// <param name="citiesViewsStatistic">Cities views statistic.</param>
        /// <returns>Task result.</returns>
        [Authorize(Roles = UserRoles.Administrator)]
        public async Task<IActionResult> CitiesStatistic(CitiesViewsStatistic citiesViewsStatistic)
        {
            ViewBag.CitiesViewsStatistic = citiesViewsStatistic;
            return View(_mapper.Map<IEnumerable<CityViewsModel>>(await _adsManager.GetCitiesStatistic()));
        }

        /// <summary>
        /// Cities statistic.
        /// </summary>
        /// <param name="citiesViewsStatistic">Cities views statistic.</param>
        /// <returns>Task result.</returns>
        [Authorize]
        public async Task<IActionResult> RentCountOfRoomStatistic()
        {
            return View(_mapper.Map<IEnumerable<RentCountOfRoomStatisticView>>(await _adsManager.GetCountOfRoomsAdsStatistic()));
        }

        /// <summary>
        /// Create view.
        /// </summary>
        /// <returns>Redirect to create page.</returns>
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.Regions = new SelectList(
                new List<string>
                {
                    "Любая область",
                    "Брестская область",
                    "Витебская область",
                    "Гомельская область",
                    "Гродненская область",
                    "Минская область",
                    "Могилёвская область",
                });

            ViewBag.RoomsCount = new SelectList(
                new List<string>
                {
                    string.Empty,
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                });
            return View();
        }

        /// <summary>
        /// Edit view.
        /// </summary>
        /// <param name="id">Unique key.</param>
        /// <returns>Redirect to edit page.</returns>
        [Authorize]
        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                var user = _usersManager.FindByEmail(User.Identity.Name);
                var ad = await _adsManager.GetAllRentalAdInfo(id);

                if (ad.RentalAd.UserId.Equals(user.Id) || User.IsInRole(UserRoles.Administrator))
                {
                    var editView = new CreateView
                    {
                        Id = ad.RentalAd.Id,
                        Address = ad.RentalAd.Address,
                        Bathroom = ad.RentalAd.Bathroom,
                        Description = ad.RentalAd.Description,
                        District = ad.RentalAd.District,
                        Facilities = ad.RentalAd.Facilities,
                        Floor = ad.RentalAd.Floor,
                        KitchenArea = ad.RentalAd.KitchenArea,
                        LandArea = ad.RentalAd.KitchenArea,
                        LivingArea = ad.RentalAd.LivingArea,
                        Locality = ad.RentalAd.Locality,
                        Notes = ad.RentalAd.Notes,
                        Region = ad.RentalAd.Region,
                        RentalType = (BLLAdsTypeMenu)ad.RentalAd.RentalType,
                        RentCountOfRooms = ad.RentalAd.RentCountOfRooms,
                        TotalArea = ad.RentalAd.TotalArea,
                        TotalCountOfRooms = ad.RentalAd.TotalCountOfRooms,
                        TotalFloors = ad.RentalAd.TotalFloors,
                        XMapCoordinate = ad.RentalAd.XMapCoordinate,
                        YMapCoordinate = ad.RentalAd.YMapCoordinate,
                    };

                    if (ad.RentalAd is DailyRentalAd)
                    {
                        var dailyAd = ad.RentalAd as DailyRentalAd;
                        editView.USDPricePerDay = dailyAd.USDPricePerDay;
                        editView.USDPricePerPerson = dailyAd.USDPricePerPerson;
                        editView.BYNPricePerDay = dailyAd.BYNPricePerDay;
                        editView.BYNPricePerPerson = dailyAd.BYNPricePerPerson;
                    }
                    else
                    {
                        var longTermAd = ad.RentalAd as LongTermRentalAd;
                        editView.BYNPrice = longTermAd.BYNPrice;
                        editView.USDPrice = longTermAd.USDPrice;
                    }

                    ViewBag.PhotosCount = ad.Photos.Count();

                    ViewBag.Regions = new SelectList(
                        new List<string>
                        {
                    "Любая область",
                    "Брестская область",
                    "Витебская область",
                    "Гомельская область",
                    "Гродненская область",
                    "Минская область",
                    "Могилёвская область",
                        });

                    ViewBag.RoomsCount = new SelectList(
                        new List<string>
                        {
                    string.Empty,
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",

RentalOfProperty/RentalOfProperty.WebUserInterface/Views/Shared/_Layout.cshtml
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var textInfo = CultureInfo.CurrentUICulture.TextInfo;

    //Get json languages list
    string jsonLanguages = JsonSerializer.Serialize(LocOptions.Value.SupportedUICultures
    .Select(c => textInfo.ToTitleCase(c.NativeName))
    .ToArray());

    //Get json cultures list
    string jsonCultures = JsonSerializer.Serialize(LocOptions.Value.SupportedUICultures
        .Select(c => c.Name)
        .ToArray());

    //Get url to query
    var jsonUrl = JsonSerializer.Serialize(Url.Action("SetLanguage", "Settings"));

    //Get load image url
    var loadImageUrl = JsonSerializer.Serialize(Url.Action("GetAvatarPath", "Users"));
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Users/Users.css" />
    <script src="https://api.mqcdn.com/sdk/mapquest-js/v1.3.2/mapquest.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <link type="text/css" rel="stylesheet" href="https://api.mqcdn.com/sdk/mapquest-js/v1.3.2/mapquest.css" />
</head>
<body class="bg-secondary">
    <header class="bg-primary container">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <a asp-controller="Home" asp-action="Index" class="navbar-brand">@Localizer["RentalOfProperty"]</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    @if (User.IsInRole(UserRoles.Administrator))
                    {
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size:11pt">
                                    @Localizer["LoadAds"]
                                </button>
                                <div class="dropdown-menu">
                                    <form asp-controller="Ads" asp-action="LoadDataFromSource" asp-route-dataSourceMenuItem="@LoadDataFromSourceMenu.GoHomeByLongTermAds"
                                          data-ajax="true"
                                          data-ajax-method="POST"
                                          data-ajax-mode="replace"
                                          data-ajax-update="#loadResult">
                                        <button class="dropdown-item" type="button" onclick="loadData('loadData-1', '@Localizer["UpdateConfirm"]')">@Localizer["GoHomeByLongTermAds"]</button>
                                        <input type="submit" class="d-none" id="loadData-1" />
                                    </form>
                                    <form asp-controller="Ads" asp-action="LoadDataFromSource" asp-route-dataSourceMenuItem="@LoadDataFromSourceMenu.RealtByLongTermAds"
                                          data-ajax="true"
                                          data-ajax-method="POST"
                                          data-ajax-mode="replace"
                                          data-ajax-update="#loadResult">
                                        <button class="dropdown-item" type="button" onclick="loadData('loadData-2', '@Localizer["UpdateConfirm"]')">@Localizer["RealtByLongTermAds"]</button>
                                        <input type="submit" class="d-none" id="loadData-2" />
                                    </form>
                                    <form asp-controller="Ads" asp-action="LoadDataFromSource" asp-route-dataSourceMenuItem="@LoadDataFromSourceMenu.GoHomeByDailyAds"
                                          data-ajax="true"
                                          data-ajax-method="POST"
                                          data-ajax-mode="replace"
                                          data-ajax-update="#loadResult">
                                        <button class="dropdown-item" type="button" onclick="loadData('loadData-3', '@Localizer["UpdateConfirm"]')">@Localizer["GoHomeByDailyAds"]</button>
                                        <input type="submit" class="d-none" id="loadData-3" />
                                    </form>
                                    <form asp-controller="Ads" asp-action="LoadDataFromSource" asp-route-dataSourceMenuItem="@LoadDataFromSourceMenu.RealtByDailyAds"
                                          data-ajax="true"
                                          data-ajax-method="POST"
                                          data-ajax-mode="replace"
                                          data-ajax-update="#loadResult">
                                        <button class="dropdown-item" type="button" onclick="loadData('loadData-4', '@Localizer["UpdateConfirm"]')">@Localizer["RealtByDailyAds"]</button>
                                        <input type="submit" class="d-none" id="loadData-4" />
                                    </form>
                                </div>
                            </div>
                        </li>
                        @if (User.IsInRole(UserRoles.Administrator))
                        {
                            <li class="nav-item">
                                <a class="btn btn-secondary" asp-controller="Ads" asp-action="AdsByType" asp-route-adsTypeMenuItem="@AdsTypeMenu.AdsForPublish">@Localizer["Publishing"]</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <div class="dropdown">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        @Localizer["Statistic"]
                                    </button>
                                    <div class="dropdown-menu">
                                        @if (User.IsInRole(UserRoles.Administrator))
                                        {
                                            <a class="dropdown-item" asp-controller="Ads" asp-action="CitiesStatistic" asp-route-citiesViewsStatistic="@CitiesViewsStatistic.LongTermAds">@Localizer["TopLongTermAds"]</a>
                                            <a class="dropdown-item" asp-controller="Ads" asp-action="CitiesStatistic" asp-route-citiesViewsStatistic="@CitiesViewsStatistic.DailyAds">@Localizer["TopDailyAds"]</a>
                                        }
                                        <a class="dropdown-item" asp-controller="Ads" asp-action="RentCountOfRoomStatistic">@Localizer["NumberOfAdsPerNumberOfRooms"]</a>
                                    </div>
                                </div>
                            </li>
                        }
                    }
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown mr-2">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @textInfo.ToTitleCase(CultureInfo.CurrentUICulture.NativeName)
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" id="language-menu">
                        </div>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</button>
                                <div class="dropdown-menu w-100 text-center">
                                    <a asp-controller="Ads" asp-action="AdsByType" asp-route-adsTypeMenuItem="@AdsTypeMenu.MyAds" class="dropdown-item">@Localizer["MyAds"] </a>
                                    <a asp-controller="Ads" asp-action="AdsByType" asp-route-adsTypeMenuItem="@AdsTypeMenu.FavoriteAds" class="dropdown-item">@Localizer["MyFavourites"]</a>
                                    <a asp-controller="Users" asp-action="EditUserData" class="dropdown-item">@Localizer["UpdatePersonalData"]</a>
                                    <a asp-controller="Users" asp-action="ChangePassword" class="dropdown-item">@Localizer["UpdatePassword"]</a>
                                    <form asp-controller="Users" asp-action="LoadAvatarImage" enctype="multipart/form-data">
                                        <input type='file' name="file" class="d-none" id="avatarImage" accept=".jpg, .jpeg, .png">
                                        <button type="button" class="dropdown-item" onclick="downloadImage('avatarImage', 'loadAvatarImage','@Localizer["IncorrectImageFormat"]')">@Localizer["UpdatePhoto"]</button>
                                        <button type='submit' class="d-none" id="loadAvatarImage"></button>
                                    </form>
                                    <form asp-controller="Users" asp-action="LogOff">
                                        <button type="submit" class="dropdown-item">@Localizer["LogOff"]</button>
                                    </form>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item dropdown mr-2" id="avatar">

                        </li>
                    }
                    else
                    {
                        <li class="nav-item mr-2">
                            <a asp-controller="Users" asp-action="Registration" class="btn btn-outline-success btn-light">@Localizer["Registration"]</a>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline my-2 my-lg-0">
                                <a asp-controller="Users" asp-action="Authorization" class="btn btn-outline-success btn-light">@Localizer["SignIn"]</a>
                            </form>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="bg-white container">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <footer class="footer text-white">
        <div class="bg-primary container text-center">
            &copy; @DateTime.Now.Year - @Localizer["RentalOfProperty"]
        </div>
    </footer>
    <script src="/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.js"></script>
    <script src="/lib/jquery/jquery.js"></script>
    <script src="/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>
    <script src="/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/js/_Layout.js" asp-append-version="true"></script>
    <script>
    let languages = JSON.parse(JSON.stringify(@Html.Raw(jsonLanguages)));
    let url = JSON.parse(JSON.stringify(@Html.Raw(jsonUrl)));
    let cultures = JSON.parse(JSON.stringify(@Html.Raw(jsonCultures)));
    let loadUrl = JSON.parse(JSON.stringify(@Html.Raw(loadImageUrl)));

    callAvatarQuey(loadUrl);
    createLanguagesList(languages, cultures, url);
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>